apiVersion: apps/v1
kind: Deployment
metadata:
  name: periodsubscribe
  labels:
    app: periodsubscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: periodsubscribe
  template:
    metadata:
      labels:
        app: periodsubscribe
    spec:
      containers:
        - name: periodsubscribe
          image: "username/periodsubscribe:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
