apiVersion: apps/v1
kind: Deployment
metadata:
  name: publication
  labels:
    app: publication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publication
  template:
    metadata:
      labels:
        app: publication
    spec:
      containers:
        - name: publication
          image: "username/publication:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
